# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-03 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subName', models.CharField(max_length=100)),
                ('semester', models.CharField(choices=[('I/I', 'first semester'), ('I/II', 'second semester'), ('II/I', 'third semester'), ('II/II', 'fourth semester'), ('III/I', 'fifth semester'), ('III/II', 'sixth semester'), ('IV/I', 'seventh semester'), ('IV/II', 'eighth semester')], max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='practical',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicals.Subject'),
        ),
    ]
