# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-05 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practicals', '0003_auto_20161105_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='prac',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='practicals.Practical'),
        ),
    ]
