# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-05 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practicals', '0004_photo_prac'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='prac',
            new_name='practical',
        ),
    ]
