# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-05 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicals', '0006_remove_subject_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(height_field=500, upload_to='', width_field=300),
        ),
    ]
