# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practicals', '0007_auto_20161105_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='practical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicals.Practical'),
        ),
    ]
